"""Agregar tabla de mensajes

Revision ID: 163506fcdd36
Revises: 3247174e0b1a
Create Date: 2025-07-21 12:08:42.108031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '163506fcdd36'
down_revision = '3247174e0b1a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Solo crear la tabla de mensajes - no tocar las demás tablas existentes
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_emisor_id', sa.Integer(), nullable=True),
    sa.Column('usuario_receptor_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.NVARCHAR(length=200), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('tipo', sa.NVARCHAR(length=50), nullable=True),
    sa.Column('prioridad', sa.NVARCHAR(length=20), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadatos', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_emisor_id'], ['Usuarios.codigo'], ),
    sa.ForeignKeyConstraint(['usuario_receptor_id'], ['Usuarios.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensajes_id'), 'mensajes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Solo eliminar la tabla de mensajes
    op.drop_index(op.f('ix_mensajes_id'), table_name='mensajes')
    op.drop_table('mensajes')
    # ### end Alembic commands ###
