from sqlalchemy import Boolean, Column, Integer, String, Float,DateTime
from ...database import Base

class Articulos(Base):
    __tablename__ = "Articulos"

    Codigo = Column(Integer, primary_key=True)
    EAN = Column(Float)
    Descripcion = Column(String(50))
    DescripcionCorta = Column(String(20))
    PrecioCosto = Column(Float)
    PrecioVenta = Column(Float)
    Margen = Column(Float)
    IVA = Column(Integer)
    EsCombo = Column(Boolean)
    Proveedor = Column(Integer)
    Departamento = Column(Integer)
    Marca = Column(Integer)
    Familia = Column(Integer)
    UxB = Column(Integer)
    HabilCajas = Column(Boolean)
    HabilEstad = Column(Boolean)
    HabilStock = Column(Boolean)
    HabilOC = Column(Boolean)
    HabilBalanzas = Column(Boolean)
    BalDiasVto = Column(Integer)
    BalCodigo = Column(Integer)
    Tipo = Column(String(1))
    CodigoEnvase = Column(Integer)
    FechaModificacion = Column(DateTime)
    FechaAlta = Column(DateTime)
    HoraModificacion = Column(String(8))
    Transmitido = Column(Boolean)
    Deposito = Column(Integer)
    PresentacionCantidad = Column(Float)
    PresentacionUnidad = Column(String(2))
    Ruteo = Column(String(15))
    Alfa = Column(String(20))
    Peso = Column(Float)
    StockMinimo = Column(Float)
    CxB = Column(Integer)
    DescuentoXCaja = Column(Float)
    ImpInterno = Column(Float)
    ArMargenTeorico = Column(Float)
    CuentaContable = Column(Float)
    SubFamilia = Column(Integer)
    DiasAlVto = Column(Integer)
    MargenIIBB = Column(Float)
    MargenOtrosImp = Column(Float)
    ModeloEtiqueta = Column(String(50))
    CantidadEtiquetas = Column(Integer)
    CxP = Column(Integer)
    CxPP = Column(Integer)
    GeneraRemitoComponentes = Column(Boolean)
    Serializado = Column(Boolean)
    sector= Column(Integer)